### ISSUE TITLE
Can't get JOptionPane to work

### ISSUE THREAD

**Issue by aldenhart** [damellis/gctrl#4]
Thanks so much for this piece of work. This will help a lot. So now the issue. The selectSerialPort routine fails on my OSX 10.6.8 machine with Processing 1.5.1 where the dialog box shows up with no data in the frame. The header says "Select serial port" as it's supposed to, but the frame is blank, with no text or buttons. 

I can get the following code to work in the selectSerialPort routine, so it looks like the swing class is loading:

  JOptionPane.showMessageDialog(frame,
    "Eggs are not supposed to be green.",
    "A plain message",
    JOptionPane.PLAIN_MESSAGE);

Have you seen anything like this or have any suggestions? Perhaps a library revision issue?

BTW: I reverted to your second push and got things working - but obviously I'd like to get this one worked out.

Thanks

Alden Hart

**Comment by damellis** [comment]
I've seen this, too.  Just hold the key on the keyboard down longer (e.g. until the dialog box appears).  It should work.  No idea why.

**Comment by nadya** [comment]
Hey Alden,
Have you tried holding the 'p' down for a longer amount of time to select the port?  We found it didn't work if we pressed it too quickly for some reason.
Nadya

**Comment by aldenhart** [comment]
Thanks for the responses. Now I see it how it works. So it looks like the key must be held down for the time it takes Serial.list() to run. Perhaps there's a way to get serial list into a static structure beforehand and select off of that. As a Processing noob I'm not sure how or if this is possible. I might monkey around a bit. Barring that, perhaps the fix is changing this line in draw():

  text("p: select serial port (press and hold)", 12, y); y += dy;

P.S. I didn't mean to close this issue. Not sure how that happened.

I just tried this, which worked, but didn't fix the short-press issue:

  String[] ports = Serial.list();

  String result = (String) JOptionPane.showInputDialog(this,
    "Select the serial port that corresponds to your Arduino board.",
    "Select serial port",
    JOptionPane.PLAIN_MESSAGE,
    null,
    ports,
//    Serial.list(),
    0);

So perhaps the (press and hold) solution is best.
